# Generated by Django 4.2.9 on 2024-02-01 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('date_of_pub', models.DateTimeField(verbose_name='Published Date')),
                ('is_deleted', models.BooleanField(default=False)),
                ('genre', models.CharField(choices=[('horror', 'horror'), ('self help', 'self help'), ('adventure', 'adventure'), ('others', 'others')], default='horror', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_related', to='testmodels.author')),
            ],
            options={
                'verbose_name': 'book',
                'ordering': ['date_of_pub'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('book', models.ManyToManyField(to='testmodels.book')),
            ],
            options={
                'verbose_name': 'collection',
                'db_table': 'book_collection',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_related', to='testmodels.publisher'),
        ),
        migrations.AddField(
            model_name='author',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_related', to='testmodels.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('author', 'title', 'date_of_pub')},
        ),
    ]
