# Generated by Django 4.2.9 on 2024-01-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodels', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('book', models.ManyToManyField(to='testmodels.book')),
            ],
        ),
    ]
