# Generated by Django 5.0.1 on 2024-01-31 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testmodels", "0006_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publisher_related",
                to="testmodels.publisher",
            ),
        ),
    ]
