# Generated by Django 5.0.1 on 2024-02-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testmodels", "0007_alter_book_publisher"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
